# Manually copied from https://github.com/alphagov/govuk-content-schemas
- case_study
- coming_soon
- contact
- detailed_guide
- document_collection
- email_alert_signup
- fatality_notice
- financial_release
- financial_releases_campaign
- financial_releases_geoblocker
- financial_releases_index
- financial_releases_success
- finder
- finder_email_signup
- hmrc_manual
- hmrc_manual_section
- html_publication
- mainstream_browse_page
- manual
- manual_section
- placeholder
- policy
- publication
- service_manual_guide
- service_manual_service_standard
- service_manual_topic
- special_route
- specialist_document
- statistics_announcement
- take_part
- topic
- topical_event_about_page
- travel_advice
- travel_advice_index
- unpublishing
- working_group
